spring:
  datasource:
    url: jdbc:mysql://localhost:3316/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: MyPass1234!
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    maxActive: 20
    minIdle: 1
    maxWait: 6000
    validationQuery: SELECT 1 FROM DUAL
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 25200000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    logAbandoned: true
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    removeAbandonedTimeoutMillis: 1800000

#log4j:
#  level:
#    root: INFO
#    org:
#      springframework:
#        web: DEBUG
#  pattern:
#    console: "%d - %msg%n"
